### ISSUE TITLE
Bulma navbar weird issue

### ISSUE THREAD

**Issue by mikestephens** [hash-gaming/slackproval#21] opened 2017-11-26 06:23 UTC
![funky](https://user-images.githubusercontent.com/1581475/33237695-12156dc6-d22f-11e7-82c4-7dfb5939961c.gif)

So for some reason the navbar when in the mobile mode will not work until a page refresh. I think it _might_ have to do with having 2 different layouts and the custom JS that had to be made here: https://github.com/hash-gaming/slackproval/blob/848704445e8d078dd74ffd5e22caf3defadbe4c0/app/assets/javascripts/application.js#L18-L41

**Comment by YashdalfTheGray** [comment] 2017-12-01 07:25
Alright so looked into this and figured out what the issue is. The `'DOMContentLoaded'` event only fires once and those buttons aren't in the DOM at the point when it fires so it doesn't set up the click listener for any of the buttons. 

I'm too tired to set up event delegation for this right now but this weekend probably, I'll set up some event delegation so that we don't have to rely on the `'DOMContentLoaded'` event to set up click listeners.

**Comment by YashdalfTheGray** [comment] 2017-12-04 01:12
Imma close this. This was fixed with #22

**Closed by YashdalfTheGray** 2017-12-04 01:12 UTC
Labels: bug
